name: music_player
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/RelaxingInstrumentals/
    - assets/Today_Hit/
    - assets/Workout_Energy/


